name: Build and Publish Prebuilt Binaries

on:
  release:
    types: [created]
    
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows
            os: windows-latest
          - name: windows-x86
            os: windows-latest
            cmake_args: -A Win32
          - name: macos
            os: macos-latest
          - name: linux
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.name }}
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - uses: lukka/get-cmake@latest
      
      - name: Build
        run: |
          cmake -B build -S . ${{ matrix.cmake_args }} -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_TESTS=OFF -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build --config Release

      - uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: ${{ matrix.name }}-${{ github.event.release.tag_name }}.zip
          directory: build/bin/

      - uses: softprops/action-gh-release@v2
        with:
          files: build/bin/${{ matrix.name }}-${{ github.event.release.tag_name }}.zip
          append_body: true
          fail_on_unmatched_files: true
